version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flowo_db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./flowo-backend/init_script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend-dev:
    build:
      context: ./flowo-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=flowo_db
      - REDIS_ADDR=redis:6379    
      - REDIS_PASSWORD=  
      - RETRY_ATTEMPTS=10
      - RETRY_DELAY=10
    volumes:
      - ./flowo-backend:/app
      - /app/main  # Exclude the built binary from volume mount
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    restart: on-failure:5

  frontend-dev:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"        # Vite dev server + HMR
      - "9229:9229"        # Node inspector (attach from VSCode/Chrome)
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"   # reliable file watching in Docker
      WATCHPACK_POLLING: "true"
      DEBUG: "vite:*"               # verbose Vite server logs
      NODE_OPTIONS: "--enable-source-maps --inspect=0.0.0.0:9229"  # debugger + stack traces
      VITE_API_BASE_URL: "http://localhost:8081/api/v1"         # API calls to backend
      VITE_DEBUG: "true"              # turn on client-side logger
    volumes:
      - ./flowo-frontend:/app
      - frontend_node_modules:/app/node_modules
    command: >
      sh -c "
        corepack enable &&
        corepack prepare yarn@1.22.22 --activate &&
        ( [ -f yarn.lock ] && yarn install --frozen-lockfile || yarn install ) &&
        yarn vite --host --logLevel info --debug
      "
    depends_on:
      - backend-dev
    networks:
      - app-network

volumes:
  mysql_data: 
  frontend_node_modules:

networks:
  app-network:
    driver: bridge