base_url: "http://localhost:8081"
timeout_ms: 15000
headers:
  Content-Type: application/json

auth:
  bearer_token: "" # set if needed

http:
  max_idle_conns: 256
  max_idle_conns_per_host: 256
  idle_conn_timeout_ms: 30000
  insecure_skip_tls_verify: false

endpoints:
  - name: health
    method: GET
    path: /health
    weight: 1
  - name: list_products
    method: GET
    path: /api/v1/products
    weight: 3
  - name: list_recommendations
    method: GET
    path: /api/v1/recommendations
    weight: 1

test:
  mode: fixed # fixed | ramp
  duration_sec: 30
  total_requests: 0  # 0 means unlimited during duration
  concurrency: 20
  global_rate_limit_per_sec: 0  # 0 means unlimited

  # ramp mode options
  max_concurrency: 200
  step: 20
  step_duration_sec: 30
  max_error_rate: 0.01
  max_p95_ms: 1000

report:
  out_dir: tools/perf/reports
  formats: ["json", "md"]
  include_per_endpoint: true


