version: "3.9"

services:
  web:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"        # Vite dev server + HMR
      - "9229:9229"        # Node inspector (attach from VSCode/Chrome)
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"   # reliable file watching in Docker
      WATCHPACK_POLLING: "true"
      DEBUG: "vite:*"               # verbose Vite server logs
      NODE_OPTIONS: "--enable-source-maps --inspect=0.0.0.0:9229"  # debugger + stack traces
      # VITE_API_BASE_URL: "http://localhost:8081/api/v1"         # if you use absolute API calls
      VITE_DEBUG: "true"              # (optional) turn on your client-side logger
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "
        corepack enable &&
        corepack prepare yarn@1.22.22 --activate &&
        ( [ -f yarn.lock ] && yarn install --frozen-lockfile || yarn install ) &&
        yarn vite --host --logLevel info --debug
      "

volumes:
  node_modules:
