version: "3.9"

services:
  web:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"               # Vite dev server + HMR
    environment:
      - CHOKIDAR_USEPOLLING=true  # more reliable file watching in Docker
      # - TAILWIND_MODE=watch     # uncomment if you're on Tailwind v3
    volumes:
      - .:/app                    # mount your source code
      - node_modules:/app/node_modules  # keep node_modules inside container
    command: >
      sh -c "
        corepack enable &&
        corepack prepare yarn@1.22.22 --activate &&
        ( [ -f yarn.lock ] && yarn install --frozen-lockfile || yarn install ) &&
        yarn run dev --host
      "

volumes:
  node_modules:
