FROM golang:alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

RUN go install github.com/air-verse/air@latest

RUN go install github.com/swaggo/swag/cmd/swag@v1.8.12

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8081

CMD ["air", "-c", ".air.toml"]